FROM python:3.10-slim-bullseye

WORKDIR /wine

COPY ./requirements-onnx.txt /wine/requirements-onnx.txt

RUN pip install --no-cache-dir -U pip wheel setuptools
RUN pip install --no-cache-dir -r /wine/requirements-onnx.txt

COPY ./api /wine/api
COPY ./schemas /wine/schemas
COPY ./onnx_model /wine/onnx_model

EXPOSE 8000